### ISSUE TITLE
add support for "clusterctl move"

### ISSUE THREAD

**Issue by haiwu** [kubernetes-sigs/cluster-api-addon-provider-helm#103]
**User Story**

As a user I would like to be able to use "clusterctl move" to backup/restore/move cluster api configs to another place/cluster. To use caaph to replace ClusterResourceSet for network cni deployment. 

It seems "clusterctl move" currently works ok with ClusterResourceSet, but I don't see yaml being generated for hrp/hcp. 

**Detailed Description**

clusterctl move to also work with hrp/hcp. 

**Anything else you would like to add:**

none

/kind feature

**Comment by Jont828** [comment]
Thanks for the feedback! Which version of Cluster API/clusterctl are you using by the way? I don't believe CAAPH would be supported in clusterctl prior to CAPI v1.5.

**Comment by Jont828** [comment]
I opened a PR with one way we could try to solve this issue. The alternative would be to document for users to add the label themselves, which is kind of awkward IMO. WDYT?
