### ISSUE TITLE
Update helm values of an application which was installed with Helmchartproxy/Helmreleaseproxy

### ISSUE THREAD

**Issue by blackbaddl13** [kubernetes-sigs/cluster-api-addon-provider-helm#135]
**User Story**

As an operator I would like to be able to update helm values of a deployment after installation. 

**Detailed Description**

As an operator, I aim to update the helm values of an installed application effortlessly. This necessity arises from our environment where numerous clusters operate seamlessly with standard values, yet a handful require additional configurations. We envision incorporating a values template within the Helmchartproxy, serving as a standard template that is only customized in exceptional scenarios. Something similar to the functionality provided by the `helm upgrade` command for updating values.

Traefik deployment is a good example for that. Most of our clusters and applications work on just an "web secure" entry point but in some cases we need to add an ssh service for example. 
So it would be great to add these information among other things to the deployment or the helmreleaseproxy

```
additionalArguments:
  - "--entrypoints.ssh.address=:2222" 

ports:
  ssh:
    port: 2222 
    expose: true
    exposedPort: 2222  
    protocol: TCP
```

We want to avoid messing up the helm logic here so we think this needs to be integrated into the Helmchart-/Helmreleaseproxy in some case

**Anything else you would like to add:**

It's plausible that the desired functionality already exists or is not desired, and there might be a misunderstanding on our part, as we haven't discovered a method to implement this workflow yet. If such functionality is available, gaining further insights would be great

/kind feature

**Comment by Jont828** [comment]
To clarify, are you saying that you want to wait for the HelmReleaseProxy resource to be created, and edit an additional field to override the valuesTemplate from HelmChartProxy? If you can tell which clusters need the additional argument based on the Cluster object, i.e. a label, you could try something like this:

```
entrypoints:
  ssh:
    address: {{if hasKey .Cluster.metadata.labels "useSSHAddress"}}2222{{else}}{{end}}
```

**Comment by blackbaddl13** [comment]
Thank you, this was not the workflow I expected or how I understood it should work. But that's great, working as expected.
