### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by zahradehghanpur** [kubernetes-sigs/cluster-api-addon-provider-helm#142]
I got the bellow error when I want to install caaph :

```
Error response from daemon: manifest for registry.k8s.io/cluster-api-helm/cluster-api-helm-controller:v0.1.1-alpha.0 not found: manifest unknown: Failed to fetch "v0.1.1-alpha.0"
```

**Comment by nikParasyr** [comment]
Looks similar to => https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/129

**Comment by tuxtof** [comment]
problem fixed @Jont828 you can close the ticket

**Comment by Jont828** [comment]
Thanks for getting this sorted!
