### ISSUE TITLE
Support retry for failed helm chart installations

### ISSUE THREAD

**Issue by khatrig** [kubernetes-sigs/cluster-api-addon-provider-helm#16]
**User Story**

As a developer/user/operator, I would like to retry a failed helm installation as a helm installation might be failing due to CRDs dependent on another helm chart not being installed yet.

**Detailed Description**
CAAPH controller start helm chart execution for all helmchartproxy objects almost parallely and doesn't wait for one helmreleaseproxy to get created. This causes issues when a helm chart is dependent on CRDs deployed by the previous helm chart. The dependent helm chart stays in Failed state forever. It seems the reconciler stops once helm install command has been executed on the cluster.

**Anything else you would like to add:**
It would really help if CAAPH supported a retry count parameter(Eg. retryCount: 5). helmReleaseProxy would get retried 5 times before giving up.

/kind feature

**Comment by Jont828** [comment]
/triage accepted

This seems reasonable to me. I think when we return an error it should requeue on its own, i.e. in [this line](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/15ddeab16c4209791fe7db22c22100fed102ea40/controllers/helmreleaseproxy/helmreleaseproxy_controller.go#L91). 

However, I think if the Helm install command succeeds it will requeue every 10 minutes (I believe) to check if the Helm release spec differs from the HelmChartProxy spec. In your use case, does the dependent Helm chart get installed without error but isn't behaving properly?

**Comment by khatrig** [comment]
> However, I think if the Helm install command succeeds it will requeue every 10 minutes (I believe) to check if the Helm release spec differs from the HelmChartProxy spec. In your use case, does the dependent Helm chart get installed without error but isn't behaving properly?

In my case helm installation completes but shows **failed**  due to some dependency issues when I run `helm list`. The expectation is to retry the helm installation after some time(by default or through some flag like retryFailed: true or retryCount: 5). 
I'm guessing retry doesn't happen as there is no update in helmchartproxy spec.

**Comment by Jont828** [comment]
Ah so I think I didn't account for the case where the install succeeds but the Helm chart is in an error state -- it assumes that if there's a problem with the installation step, it would return an error. If a user configured a chart incorrectly, i.e. listening on wrong port or network address, for example, it would be up to the user to update the HelmChartProxy spec to fix the configuration.

Could you tell me a bit about what chart you're trying to install and how to repro the issue? And do you have the same issue if you manually install the Helm chart/does reinstalling fix it?

**Comment by khatrig** [comment]
I use helm to install and configure metallb. I've a custom metallb-config helm chart that configures metallb for me.  ie. create metallb CRD objects [ipaddresspool](https://metallb.universe.tf/configuration/) etc.
When I create MetalLB and metallb-config helmchartproxy, both of these get installed on the workload clusters almost instantaneously and metallb-config helm chart installation fails because metallb CRDs are not available yet.


```
helm list -A
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
metallb         metallb-system  1               2023-02-28 10:39:02.392174762 +0000 UTC deployed        metallb-0.13.7          v0.13.7    
metallb-config  metallb-system  1               2023-02-28 10:40:16.09693494 +0000 UTC  failed          metallb-config-0.2.0    0.1.0     


kl -n caaph-system -l control-plane=controller-manager -f
E0228 14:22:25.814808      14 controller.go:326] "Reconciler error" err=<
        error installing or updating chart with Helm on cluster wkcl1: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "wkcl1-bgp-adv" namespace: "" from "": no matches for kind "BGPAdvertisement" in version "metallb.io/v1beta1"
        ensure CRDs are installed first, resource mapping not found for name: "wkcl1-peers" namespace: "" from "": no matches for kind "BGPPeer" in version "metallb.io/v1beta2"
        ensure CRDs are installed first, resource mapping not found for name: "wkcl1-ippool" namespace: "" from "": no matches for kind "IPAddressPool" in version "metallb.io/v1beta1"
        ensure CRDs are installed first]
```

**Comment by khatrig** [comment]
> Gotcha thanks for elaborating. It looks like [this is the line](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/deb12be2e13c83f56353a138971dccdb63d7ff9c/controllers/helmreleaseproxy/helmreleaseproxy_controller.go#L211) where the error is coming from in the HelmReleaseProxy controller. If the controller is returning an error, it should requeue itself, so I'm thinking this might actually be a bug.
> 
> I'll try to repro this on my end -- did you set anything in the valueTemplate for either the metallb or metallb-config charts or are the default values sufficient?

I used default values

**Comment by Jont828** [comment]
Sounds good, could you post the custom chart you made as well as the HelmChartProxies for metallb and metallb-config?

**Comment by Jont828** [comment]
If you'd like, I'm happy to hop on a zoom call and pair on this together if that would be easier.
