### ISSUE TITLE
CAAPH considers an image tag as number instead of string

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-addon-provider-helm#175]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In a [CI build](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/5451/pull-cloud-provider-azure-e2e-ccm-capz-1-27/1759778067762384896) with CAPZ 1.13, cloud-node-manager crashed because image tag is like this:
```
capzci.azurecr.io/azure-cloud-node-manager:%!s(float64=7.392922e+06)
```

I checked other [logs](https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/5451/pull-cloud-provider-azure-e2e-ccm-capz-1-27/1759778067762384896/artifacts/clusters/bootstrap/resources/default/HelmChartProxy/cloud-provider-azure-chart-ci.yaml](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/5451/pull-cloud-provider-azure-e2e-ccm-capz-1-27/1759778067762384896/artifacts/clusters/bootstrap/resources/default/HelmChartProxy/cloud-provider-azure-chart-ci.yaml)), the actual image tag is `7392922`.

I believe CAAPH didn't handle the tag as a string.

Actually, before CAAPH, the similar problem happens and we use `helm --set-string`

**What did you expect to happen:**
A number tag should be corrected parsed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 1.13
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
@Jont828 do you think this is a bug in CAAPH, or can we fix this by changing this:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/v1.13.1/templates/addons/cluster-api-helm/cloud-provider-azure-ci.yaml#L28

to this:

`imageTag: "${IMAGE_TAG_CNM:-}"`

cc @mboersma

**Comment by lzhecheng** [comment]
@Jont828 I prefer to do it in code, so we don't need to update every template.

**Comment by Jont828** [comment]
@jackfrancis @lzhecheng The `valuesTemplate` field is just a string that gets passed directly to Helm, and the env var substitution for `IMAGE_TAG_CNM` happens in CAPZ I believe. So I'm not sure if this is something we can address with CAAPH. Could we try Jack's suggestion of adding quotes first to see if it works?

**Comment by lzhecheng** [comment]
> @jackfrancis @lzhecheng The `valuesTemplate` field is just a string that gets passed directly to Helm, and the env var substitution for `IMAGE_TAG_CNM` happens in CAPZ I believe. So I'm not sure if this is something we can address with CAAPH. Could we try Jack's suggestion of adding quotes first to see if it works?

I'm ok with Jack's suggestion but I just wonder if there's a solution for all such fields.

**Comment by Jont828** [comment]
I don't think there's an immediate solution that comes to mind since it seems like it's dependent on how Helm parses the values.

**Comment by lzhecheng** [comment]
I checked `cluster-api-addon-provider-helm` code and have some ideas. Please correct me if I'm wrong.

Here, it uses `ValueFiles` for the whole spec. If `IMAGE_TAG` is put under `StringValues` then it should be correctly parsed.

https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/378279b6c3d0153d1dd9d3496d2d9409d6118815/internal/helm_client.go#L260-L262

Or, if we can add quotes for numbers in `valueLookUp` in `value_substitutions.go` before returning `expandedTemplate`.

https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/378279b6c3d0153d1dd9d3496d2d9409d6118815/internal/value_substitutions.go#L75

@Jont828 @jackfrancis what do you think?

**Comment by jackfrancis** [comment]
I think adding a stringValues configuration interface to CAAPH if it doesn't already exists makes sense.

In the meantime: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4593

**Comment by Jont828** [comment]
@jackfrancis If your solution works, then I think we can open a PR to add that as documentation and close this issue then.

**Comment by jackfrancis** [comment]
I think it works!
