### ISSUE TITLE
Unable to change namespace

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-addon-provider-helm#197]
**What steps did you take and what happened:**
Deploy a HelmChartProxy and then change the namespace value.  The install gets deleted from the current namespace, but it doesn't get reinstalled to the new namespace.

I found this in the logs:

```
E0319 23:30:02.231917       1 controller.go:329] "Reconciler error" err="Unable to continue with install: CustomResourceDefinition \"applications.argoproj.io\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key \"meta.helm.sh/release-name\" must equal \"argo-cd-1710890996\": current value is \"argo-cd-1710874729\"; annotation validation error: key \"meta.helm.sh/release-namespace\" must equal \"argocd\": current value is \"default\"" controller="helmreleaseproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmReleaseProxy" HelmReleaseProxy="default/argo-cd-argoclustercaaph-wwfjf" namespace="default" name="argo-cd-argoclustercaaph-wwfjf" reconcileID="894ea010-a219-450a-9f76-eb4741c8de97"
```

**What did you expect to happen:**
At a minimum it would be more clear what is happening.  Ideally, it would just delete the install from the current namespace and install to the new namespace.

**Environment:**

- Cluster API version: 1.14.0
- Cluster API Add-on Provider for Helm version:  v0.1.1-alpha.1 
- Kubernetes version: (use `kubectl version`): docker-desktop K8s 1.29.1

/kind bug

**Comment by mboersma** [comment]
/remove-lifecycle stale

This still seems worthy of fixing IMHO.

**Comment by Jont828** [comment]
I was unable to repro this issue. I did however, reach an error trying to install it based on the HelmChartProxy we used, and by fixing the values, I got it to successfully install and change namespaces as well.

/close
