### ISSUE TITLE
Apply user-defined metadata (labels and annotations) when creating the release namespace

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-addon-provider-helm#221]
**User Story**

As a user, I would like to add metadata to the release namespace, as required by some charts [1]. A helm chart [does not add metadata to the release namespace](https://github.com/helm/helm/issues/3503), for the same reason it does not [create the release namespace](https://github.com/helm/helm/issues/5753#issuecomment-502163585).

> **[1]** The speaker pod requires elevated permission in order to perform its network functionalities.
> If you are using MetalLB with a kubernetes version that enforces [pod security admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) (which is beta in k8s 1.23), the namespace MetalLB is deployed to must be labelled...
> -- https://metallb.org/installation/#installation-with-helm

**Detailed Description**

When CAAPH creates the release namespace, it should apply user-defined metadata (labels and annotations) to the  namespace.

**Anything else you would like to add:**

_Alternatives_

1. Create the release namespace (with metadata) on the workload cluster, before creating the CAAPH resources for the release. If the cluster is based on a ClusterClass, this can be done using an [`AfterControlPlaneInitialized`](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-lifecycle-hooks#aftercontrolplaneinitialized) lifecycle hook.
1. Use a separate chart that creates a namespace, and then use that namespace as the release namespace.
1. Define a helm pre-install hook. This is a Kubernetes Job that helm creates before it creates the other resources in the release. The Job must create the namespace. 
 
_Implementation_

CAAPH [delegates](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm//blob/fa594f1a36b69e34920f8448f57c10fd8a9b4d9f/internal/helm_client.go#L159) namespace creation to the helm client. This client does not add metadata to the namespace, and helm maintainers have [made it clear](https://github.com/helm/helm/issues/5753#issuecomment-502163585) that this will not change. To be able to add metadata to the namespace, CAAPH would have to implement its own namespace creation.

/kind feature

**Comment by Jont828** [comment]
@dlipovetsky This is an interesting idea. You're correct in that currently, we just pass through the `spec.namespace` field to mimic the `--create-namespace` [option in Helm install](https://helm.sh/docs/helm/helm_install/#options). How exactly do you propose to configure the namespace metadata? Is the idea to pass through all the labels/annotations on the HelmChartProxy to the namespace? Or to add a new API field in the spec?

**Comment by dlipovetsky** [comment]
Thanks for triaging!

> Is the idea to pass through all the labels/annotations on the HelmChartProxy to the namespace?

I hadn't considered passing through labels/annotations on the HelmChartProxy. I would recommend against it, mainly because it would effectively become part of the API, but lack discoverability, and versioning, among other things.

> Or to add a new API field in the spec?

I think an API field would make sense.

**Comment by dlipovetsky** [comment]
I'd like to hear from other users who need this; are they happy with one or more of the alternatives I listed above? Do they have other alternatives? I wouldn't want CAAPH to expand its API without a clear need.

**Comment by Jont828** [comment]
> I hadn't considered passing through labels/annotations on the HelmChartProxy. I would recommend against it, mainly because it would effectively become part of the API, but lack discoverability, and versioning, among other things.

That makes sense, it would be a clever workaround but perhaps a bit too clever to be easily discovered by users. 

> I'd like to hear from other users who need this; are they happy with one or more of the alternatives I listed above? Do they have other alternatives? I wouldn't want CAAPH to expand its API without a clear need.

I haven't heard of anyone else who has this use case. Maybe worth bringing it up in Slack or CAPI office hours?

**Comment by Jont828** [comment]
@dlipovetsky Do you still need this? And if so, did you just envision adding a field like `spec.releaseNamespaceLabels` and `releaseNamespaceAnnotations`?

**Comment by Jont828** [comment]
@shineeng Helm install currently has the `--create-namespace` flag which we are using here. Are you interested in this feature to pass through metadata to the release namespace, or just creating a namespace at all?

Btw, I don't think Helm uninstall should be removing a namespace since it could be shared by other resources, though.
