### ISSUE TITLE
CAAPH Release 0.2.5

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-addon-provider-helm#276]
Release 0.2.5 - to include latest dependency updates in past 2 months

/kind feature

**Comment by mboersma** [comment]
See also kubernetes-sigs/cluster-api-provider-azure#4869

**Comment by Jont828** [comment]
I think we can do that once #272 merges!

**Comment by Jont828** [comment]
[v0.2.5 release](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/releases/tag/v0.2.5) is out!
