### ISSUE TITLE
golangci-lint failing on PRs

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-addon-provider-helm#300]
**Which jobs are failing:**

golangci-lint / lint https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/actions/runs/11438987508/job/31821729558?pr=297 for example

**Which tests are failing:**

Many `typecheck` linter errors which appear to be false positives.

**Since when has it been failing:**

At least two weeks.

/kind failing-test

**Comment by thiha-min-thant** [comment]
Hi @mboersma , could you please assign to me?

**Comment by mboersma** [comment]
I haven't been able to reproduce this locally, it seems just to happen in the prow CI environment. These don't look to me like actual linter errors; I'm not sure why they're being reported.

**Comment by thiha-min-thant** [comment]
May I know how did you run it. I can reproduce it in my local by running `make lint`. I saw an issue on `golangci-lint` repo. https://github.com/golangci/golangci-lint/issues/3718. After I update the version, no more `typecheck` error.

**Comment by mboersma** [comment]
I was just doing `golangci-lint run` with version 1.59.0 installed locally, somehow it passed. I've updated to v1.61.0 now.
