### ISSUE TITLE
Helm chart version in HCP depending on k8s version of workload cluster

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api-addon-provider-helm#40]
**User Story**

As a [developer/user/operator] I would like to be able to change the version of the helm repository in a single `HelmChartProxy` depending on the version of the workload cluster.

**Detailed Description**

For some addons such as CNIs or cloud-controllers the version of the helm chart to use is dependent on the version of the workload cluster. These addons are also crucial for the operation of the workload cluster. 

For example (versions are not the actual ones, but i hope it will make the problem clearer):
- For kubernetes 1.24.X calico might need to be installed using chart version 2.13.0
- For kubernetes 1.25.Y calico might need 2.14.0

Currently this can be done (afaik) only by creating 2 different HelmChartProxies and matching them to the k8s version (calico_1.24 using helm chart version 2.13.0 and calico_1.25 using helm chart version 2.14.0). The problem here is that when a cluster is upgraded from 1.24 -> 1.25:
- the HelmReleaseProxy mapping to calico_1.24 HCP will stop matching and calico 2.13.0 will be uninstalled
- the HelmReleaseProxy mapping to calico_1.25 will start matching and calico 2.14.0 will be installed
(the order of installation/deletion can be different and it can cause different issues)

Completely uninstalling the CNI can be very problematic (similar for cloud-controllers). In reality, i just want CAAPH to be "smart enough" to just bump the chart version and run a `helm upgrade`, instead of uninstalling and reinstalling such a crucial addon.

**Anything else you would like to add:**
- I'm not sure what a good approach for this would be
- I'm also not sure whether I'm missing something and whether this can be achieved in a different way
- `ValuesTemplate` might also need to be different based on the k8s version but i think this is already doable with some formatting and using the .Cluster... variables

/kind feature

**Comment by Jont828** [comment]
This is something I discussed with @fabriziopandini and @jackfrancis in the initial design, and we're planning on looking into it as part of an additional iteration of the prototype. I found that some Helm charts like cloud-provider-azure already have [existing logic](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/helm/cloud-provider-azure/templates/cloud-provider-azure.yaml) for matching the chart version with the K8s version, so in that case some charts would likely work out of the box.

I'm just brainstorming, but I wonder if we can add an additional field like `versionMap` which could look something like this. The idea would be that if a regex in the map matches the K8s version, we install/upgrade to that version and if isn't in the map, we just default to the version specified in the `version` field. What do you think about this?

```
versionMap:
  1.24.*: 2.1.3.0
  1.25.*: 2.14.0
```

**Comment by nikParasyr** [comment]
> I found that some Helm charts like cloud-provider-azure already have [existing logic](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/helm/cloud-provider-azure/templates/cloud-provider-azure.yaml) for matching the chart version with the K8s version

This is interesting. Although i'd say we can't expect all upstream helm charts to have such logic and adding that logic could be a lot of work for users.

>  I'm just brainstorming, but I wonder if we can add an additional field like versionMap which could look something like this. The idea would be that if a regex in the map matches the K8s version, we install/upgrade to that version and if isn't in the map, we just default to the version specified in the version field. What do you think about this?

I think this would work for my use-case. The `versionMap` should be optional but have higher priority than `version` when it's set. It would be beneficial if CAAPH automatically picks up the version and not through labels ( this will be easier from user perspective, addons will be deployed faster and will not require users to update a label after the upgrade).

**Comment by nikParasyr** [comment]
> I think we should also consider the use case scope for this add on. If the primary goal is a one-time install,

by add-on i assume you mean CAAPH. For one-time installs there is also `ClusterResourceSet` from capi itself. Although it doesn't use Helm. From the docs of this repo:
> by providing a solution for managing the installation, configuration, upgrade, and deletion of Cluster add-ons using Helm charts

CAAPH already does more than just one-time installs. I was expecting that "smooth" upgrades of add-ons would fall under this scope as well. If this is not the case, i'd like to know now because this is a blocker for us. I understand though that it might take some time to be implemented (if its considered in-scope).

@Jont828 Do you think this is in scope of CAAPH?

**Comment by dtzar** [comment]
@nikParasyr - The scope for this project is still open for discussion, which is why I said we should _consider_ it for this add on (yes I meant CAAPH).  We should consider upgrade.  I do think there is a line at some point where alternative solutions are more appropriate compared to CAAPH.  I believe the topic of scope would be a great discussion on the community call, but as I already mentioned to you I'm also happy to have a 1:1 conversation to better understand your requirements/use case.  

Furthermore, as this is an open-source project - especially a new one - we are looking for more contributors and maintainers.

**Comment by Jont828** [comment]
@nikParasyr For some additional context on scope -- we plan on iterating over the design of this project going forward, and we're currently working on the first iteration with a limited scope (essentially everything listed in the [add-on proposal)](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220712-cluster-api-addon-orchestration.md). But the scope of future iterations is up to the community -- as David said, I think it would be good to bring up your concerns about versions in the community call to get a temp read.

**Comment by dtzar** [comment]
@nikParasyr - I proactively added this as a discussion topic for the [Cluster API meeting agenda ](https://docs.google.com/document/d/1ushaVqAKYnZ2VN_aa3GyKlS4kEd6bSug13xaXOakAQI/) next week 3/29. Hopefully we will see you there.

**Comment by Jont828** [comment]
@nikParasyr Is this something you still need?

**Comment by nikParasyr** [comment]
@Jont828 I don’t need it atm. 

I still think that adding the functionality on upstream helm charts that don’t have it is quite some work. So I’d like to have it but I don’t need it.

**Comment by dtzar** [comment]
There are also other ways to accomplish the same goal for rollout utilizing GitOps principles.  IMO I believe this functionality should be left to other means than CAAPH itself.
