### ISSUE TITLE
Missing container images of release

### ISSUE THREAD

**Issue by batistein** [kubernetes-sigs/cluster-api-addon-provider-helm#61]
**What steps did you take and what happened:**
I tried to deploy the release v0.1.0-alpha.4 but the got an ImagePullBackOff after investigating I saw that there is no image for the v0.1.0-alpha.4 tag only for v0.1.0-alpha.1.
see: https://explore.ggcr.dev/?repo=registry.k8s.io%2Fcluster-api-helm%2Fcluster-api-helm-controller

**What did you expect to happen:**
I expect to successfully deploy the CAAPH controller

**Environment:**

- Cluster API Add-on Provider for Helm version: v0.1.0-alpha.4 

/kind bug

**Comment by Jont828** [comment]
Hey, I have an [image promotion PR](https://github.com/kubernetes/k8s.io/pull/5146) for v0.1.0-alpha.4 right now and we're just waiting for it to get merged. In the meantime, you can find staging images at `gcr.io/k8s-staging-cluster-api-helm/cluster-api-helm-controller`.

**Comment by Jont828** [comment]
That PR merged, you should be able to pull the image now at `registry.k8s.io/cluster-api-helm/cluster-api-helm-controller:v0.1.0-alpha.4`!

**Comment by batistein** [comment]
@Jont828  thanks for adding the image. But I'm getting the same issue on the v0.1.0-alpha.5 
Maybe it makes sense to automate the image promotion?
