### ISSUE TITLE
Update development documentation for CNI installation

### ISSUE THREAD

**Issue by hama-25179** [kubernetes-sigs/cluster-api-addon-provider-helm#8]
When set up according to the development docs, CNI is not installed on the workload cluster.
https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/docs/development.md

If CNI is not installed, the sample HelmChartProxy of nginx-ingress will not work, so I want to install CNI automatically.
Registering HelmChartProxy of calico as a Tilt resource, developers will no longer have to worry about CNI.

May I create a pull request for the above content?
I already created a HelmChartProxy manifest of calico and a shell script to register as a Tilt resource, and improved the document.

Note that I have worked together with @hiromu-a5a on this issue.

**Comment by Jont828** [comment]
Thanks for opening this issue, I'll try to repro when I have some time. And absolutely, contributions are welcome!
