### ISSUE TITLE
HelmChartProxies with chart names that have slashes fail to reconcile

### ISSUE THREAD

**Issue by verokarhu** [kubernetes-sigs/cluster-api-addon-provider-helm#98]
**What steps did you take and what happened:**
Create a HelmChartProxy using e.g. https://docs.tigera.io/calico/latest/getting-started/kubernetes/helm#how-to

This results in the HelmChartProxy having a status of:
```
failed to create HelmReleaseProxy '' for cluster: clusters/test: HelmReleaseProxy.addons.cluster.x-k8s.io "projectcalico/tigera-operator-test-54fvf" is invalid: [metadata.generateName: Invalid value: "projectcalico/tigera-operator-test-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "projectcalico/tigera-operator-test-54fvf": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**What did you expect to happen:**
Helm chart is applied to cluster.

**Anything else you would like to add:**
It looks like https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/controllers/helmchartproxy/helmchartproxy_controller_phases.go#L173 directly copies the name without sanitizing it for forbidden characters.

**Environment:**

- Cluster API version: 1.4.4
- Cluster API Add-on Provider for Helm version: v0.1.0-alpha.7
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): v1.27.2
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by Jont828** [comment]
I believe Helm chart names don't allow slashes, actually. In your case, it looks like `projectcalico` is the repo name and `tigera-operator` would be the chart name. We don't support adding repos with names currently, instead you would need to include the `repoURL`. To install calico, check out [calico-cni.yaml](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/config/samples/calico-cni.yaml).
